In [1]:
from fastai.text.all import *

In [2]:
path = untar_data(URLs.HUMAN_NUMBERS)

In [3]:
Path.BASE_PATH = path

In [4]:
path.ls()

(#2) [Path('valid.txt'),Path('train.txt')]

In [5]:
lines = L()
with open(path/'train.txt') as f: lines += L(*f.readlines())
with open(path/'valid.txt') as f: lines += L(*f.readlines())
lines

(#9998) ['one \n','two \n','three \n','four \n','five \n','six \n','seven \n','eight \n','nine \n','ten \n','eleven \n','twelve \n','thirteen \n','fourteen \n','fifteen \n','sixteen \n','seventeen \n','eighteen \n','nineteen \n','twenty \n'...]

# Preprocessing

## Tokenisation

In [6]:
text = ' . '.join(l.strip() for l in lines)

In [8]:
text[:100]

'one . two . three . four . five . six . seven . eight . nine . ten . eleven . twelve . thirteen . fo'

In [8]:
tokens = text.split(' ')
tokens[:10]

['one', '.', 'two', '.', 'three', '.', 'four', '.', 'five', '.']

## Numericalisation

In [9]:
vocab = L(*tokens).unique()
vocab

(#30) ['one','.','two','three','four','five','six','seven','eight','nine','ten','eleven','twelve','thirteen','fourteen','fifteen','sixteen','seventeen','eighteen','nineteen'...]

In [11]:
word2idx = {w:i for i, w in enumerate(vocab)}
nums = L(word2idx[w] for w in tokens)
nums

(#63095) [0,1,2,1,3,1,4,1,5,1,6,1,7,1,8,1,9,1,10,1...]

## Self-supervising data set

In [12]:
sl = 16
seqs = L((tensor(nums[i:i+sl]), tensor(nums[i+1: i+1+sl])) for i in range(0, len(nums)-sl-1, sl))

In [14]:
seqs[0]

(tensor([0, 1, 2, 1, 3, 1, 4, 1, 5, 1, 6, 1, 7, 1, 8, 1]),
 tensor([1, 2, 1, 3, 1, 4, 1, 5, 1, 6, 1, 7, 1, 8, 1, 9]))

In [13]:
BATCHSIZE = 64

In [14]:
def group_chunks(ds, bs):
    m = len(ds) // bs
    new_ds = L()
    for i in range(m): new_ds += L(ds[i + m*j] for j in range(bs))
    return new_ds

In [15]:
cut = int(len(seqs)*0.8)
dls = DataLoaders.from_dsets(
    group_chunks(seqs[:cut], BATCHSIZE), 
    group_chunks(seqs[cut:], BATCHSIZE), 
    bs=BATCHSIZE, drop_last=True, shuffle=False)

In [18]:
len(seqs[:cut]) // BATCHSIZE

49

In [19]:
seqs[49]

(tensor([ 2, 28, 11,  1,  2, 28, 12,  1,  2, 28, 13,  1,  2, 28, 14,  1]),
 tensor([28, 11,  1,  2, 28, 12,  1,  2, 28, 13,  1,  2, 28, 14,  1,  2]))

## Vanillla RNN

In [41]:
class RNN(Module):
    def __init__(self, vocab_sz, n_hidden, sl):
        self.i_h = nn.Embedding(vocab_sz, n_hidden)
        self.h_h = nn.Linear(n_hidden, n_hidden)
        self.h_o = nn.Linear(n_hidden, vocab_sz)
        self.sl = sl
        self.h = 0

    def forward(self, x):
        outs = []
        for i in range(self.sl):
            self.h = self.h + self.i_h(x[:,i])
            self.h = F.relu(self.h_h(self.h))
            outs.append(self.h_o(self.h))
        self.h = self.h.detach()
        return torch.stack(outs, dim=1)

    def reset(self):
        self.h = 0
        

In [35]:
def loss_func(inp, targ):
    return F.cross_entropy(inp.view(-1, len(vocab)), targ.view(-1))

In [44]:
simple_rnn = RNN(len(vocab), 64, 16)

In [45]:
learn = Learner(dls, simple_rnn, loss_func = loss_func, metrics=accuracy, cbs=ModelResetter)
learn.fit_one_cycle(15, 3e-3)

In [27]:
class LSTM(Module):
    def __init__(self, vocab_size, n_layers, n_hidden, batch_size):
        self.ih = nn.Embedding(vocab_size, n_hidden)
        self.rnn = nn.LSTM(n_hidden, n_hidden, n_layers, batch_first=True) 
        self.ho = nn.Linear(n_hidden, vocab_size)
        self.h = [torch.zeros(n_layers, batch_size, n_hidden) for _ in range(2)]

    def forward(self, x):
        res, h = self.rnn(self.ih(x), self.h)
        self.h = [h_.detach() for h_ in h]
        return self.ho(res)

    def reset(self):
        for h in self.h: h.zero_()
        

In [28]:
lstm = LSTM(len(vocab), 1, 64, BATCHSIZE)
lstm_learn = Learner(dls, lstm, loss_func=CrossEntropyLossFlat(),
           metrics=accuracy, cbs=ModelResetter)
lstm_learn.fit_one_cycle(15, 1e-2)

In [39]:
class AWDLSTM(Module):
    def __init__(self, vocab_sz, n_hidden, n_layers, batch_size, drop_out_p):
        self.ih = nn.Embedding(vocab_sz, n_hidden)
        self.rnn = nn.LSTM(n_hidden, n_hidden, n_layers, batch_first=True)
        self.drop = nn.Dropout(drop_out_p)
        self.ho = nn.Linear(n_hidden, vocab_sz)
        self.ho.weight = self.ih.weight #weight tying
        self.h = [torch.zeros(n_layers, batch_size, n_hidden) for _ in range(2)]

    def forward(self, x):
        raw, h = self.rnn(self.ih(x), self.h)
        out = self.drop(raw)
        self.h = [h_.detach() for h_ in h]
        return self.ho(out), raw, out

    def reset(self):
        for h in self.h: h.zero_()

In [40]:
awd_learn = Learner(dls, AWDLSTM(len(vocab), 64, 2, BATCHSIZE, 0.5),
                loss_func=CrossEntropyLossFlat(), metrics=accuracy,
                cbs=[ModelResetter, RNNCallback, RNNRegularizer(alpha=2, beta=1)])

In [41]:
awd_learn.fit_one_cycle(15, 1e-2, wd=0.1)

In [37]:
awd_learn = Learner(dls, LMModel7(len(vocab), 64, 2, 0.5),
                loss_func=CrossEntropyLossFlat(), metrics=accuracy,
                cbs=[ModelResetter, RNNCallback, RNNRegularizer(alpha=2, beta=1)])